import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ConfettiProvider } from '@/components/providers/confettiProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'E-Learning',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return ( 
  <ClerkProvider>
    <html lang="en">
     <ConfettiProvider />
      <body className={inter.className}>{children}</body>
    </html> 
    </ClerkProvider>
  )
}

 
